services:
  app:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./config:/app/conf
    environment:
      JSON_CONFIG_PATH: /app/conf/config.json
