services:
  app:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    ports:
      - 127.0.0.1:8080:8080
    environment:
      JSON_CONFIG:
        '{
          "tokenCallbacks": [
              {   
                  "issuerId": "meshwith",
                  "tokenExpiry": 120,
                  "requestMappings": [
                      {   
                          "requestParam": "grant_type",
                          "match": "authorization_code",
                          "claims": {
                              "scope": "${scope}",
                              "aud": [
                                  "testCode" ]
                          }   
                      }   
                  ]   
              }  
          ]   
      }'
 
        
        
